---

- name: edit cluster-config
  command: /opt/splunk/bin/splunk edit cluster-config -mode slave -master_uri https://sv3-prdv-splk-001.sv.splunk.com:8089 -replication_port 9887 -secret AlAImQqD$9YY -auth admin:Splunk3r
  tags: clustering

- name: restart splunk service
  command: /opt/splunk/bin/splunk restart
  tags: service restart
