---

- hosts: stage_shc_dp
  serial: 4
  become: yes
  vars:
    user: splunk
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
    deploy_dir: apps
    clone_path: /opt/git/
#    git_project: zero-
#    splunk_apps: [ 'zero_app_mon', 'zero_dsa' ]
    user_group: wheel
    app_packages:
      - { project: 'zero-id', repo: 'zero_sites', branch: 'master'}
  roles:
    - configure_git-management
    - configure_nginx-include
# listed apps from ITSI 2.6.0 make sure to add apps that are added in later builds
#    clustered_splunk_apps: [ 'SA-ITSI-CustomModuleViz', 'DA-ITSI-STORAGE', 'DA-ITSI-APPSERVER', 'DA-ITSI-DATABASE', 'DA-ITSI-EUEM', 'DA-ITSI-LB', 'DA-ITSI-OS', 'DA-ITSI-VIRTUALIZATION', 'DA-ITSI-WEBSERVER', 'DA-ITSI-WebServices', 'itsi', 'SA-IndexCreation', 'SA-ITOA', 'SA-ITSI-ATAD', 'SA-ITSI-Licensechecker', 'SA-ITSI-MetricAD', 'SA-UserAccess', 'Splunk_SA_CIM', 'Splunk_TA_webservices' ]
