---

- hosts: stage_idx
  serial: 10
  become: yes
  vars:
    splunk_user: splunk
    user: splunk
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
  roles:
    - splunk_gen_restart