---

- hosts: stage_all
  vars:
    user: splunk
    user_group: wheel
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
  become: yes
  roles:
    - splunk-CHG-dftpass


# - include: splunk_sh_add_search-peers-srv_mon.yml
#   vars:
#     uri: https://sv3-prdv-splk-903.sv.splunk.com
#     mgmt_port: 8089

#- include: splunk_sh_install-itsi.yml
