---

- hosts: products_apl
  vars:
#    user: splunk
#    ansible_user: splunk
#    ansible_ssh_private_key_file: ~/.ssh/splunk.key
    splunk_user: splunk
#    auth_cred: admin:Splunk3r
#    installer: splunk-7.0.0-cf807dd96413-linux-2.6-x86_64.rpm 
#    url: 'http://releases.splunk.com/dl/minty_builds/7.0.0-20170817-0000/splunk-7.0.0-cf807dd96413-linux-2.6-x86_64.rpm'
  become: yes
  roles:
#    - splunk_gen_update-core
    - splunk_idx_disable_main
    
# - include: splunk_sh_add_search-peers-srv_mon.yml
#   vars:
#     uri: https://sv3-prdv-splk-903.sv.splunk.com
#     mgmt_port: 8089