---

- hosts: deploy_srv
  vars:
    user: splunk
    user_group: wheel
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
    #splunk_user: splunk
    deploy_dir: deployment-apps
    app_packages:
      - { project: 'zero-cm', repo: 'deployment_apps', branch: 'master' }
  roles:
    # - configure_host_vars
    # - splunk_gen_backup-prep
    # - splunk_gen_backup-apps
    # - splunk_gen_backup-deploy-apps
    # - splunk_gen_backup-instance
    - configure_git-management
    - splunk_uf_app_update
    - splunk_idx_update-group-apps
    - splunk_gen_update-repo-apps
    - splunk_uf_app_deploy
