---

- hosts: webdev_hec
  vars:
########## vars for auth ##########
    # user: acain
    # user_group: domain^users
########## vars for install #########
    splunk_version: 7.1.1
    os_platform: linux-2.6-x86_64.rpm
    # installer: '{{ splunk_pkg }}'
    installer: 'splunk-7.1.1-8f0ead9ec3db-linux-2.6-x86_64.rpm'
    # url: '{{ splunk_dl }}'
    url: 'http://releases.splunk.com/released_builds/7.1.1/splunk/linux/splunk-7.1.1-8f0ead9ec3db-linux-2.6-x86_64.rpm'
########## vars for os ##########
    yum_packages:
      - { name: 'syslog-ng'}
########## vars for apps ##########
    cert_file: aws_rootcert.pem
    deploy_dir: apps
    app_packages:
########## Apps for all search heads #########
      - { project: 'zero-id', repo: 'zero_IDX-cluster', branch: '{{ idx_tag }}_SEARCH', target: 'search' }
      - { project: 'zero-sb', repo: 'Splunk_TA_nix', branch: 'sz-monitor', target: 'search' }
########## Apps for all installs #########
      - { project: 'zero-id', repo: 'zero_prod', branch: 'master', target: 'all' }
      - { project: 'zero-id', repo: 'zero_dsa', branch: 'master', target: 'all' }
########## Apps for SHC deployer #########
      - { project: 'zero-id', repo: 'zero_SHC-cluster', branch: '{{ shc_tag }}_DP', target: 'shc-deployer' }
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'shc-deployer' }
########## Apps for SHC members #########
      - { project: 'zero-id', repo: 'zero_SHC-cluster', branch: '{{ shc_tag }}_SH', target: 'shc-member' }
      - { project: 'zero-id', repo: '01-gold_shc', branch: 'master', target: 'shc-member' }
      - { project: 'zero-id', repo: '01-rolemap_perm', branch: 'master', target: 'shc-member' }
      - { project: 'zero-id', repo: 'zero_auth_saml', branch: 'non-ssl', target: 'shc-member' }
      - { project: 'zero-id', repo: 'zero_rolemap', branch: 'master', target: 'shc-member' }
########## Apps for dev search #########
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'dev-sh' }
########## Apps for prod search #########
      - { project: 'zero-id', repo: 'zero_auth_saml', branch: 'master', target: 'prd-sh' }
      - { project: 'zero-id', repo: 'zero_rolemap', branch: 'master', target: 'prd-sh' }
########## Apps for IDX slaves #########
      - { project: 'zero-id', repo: 'zero_IDX-cluster', branch: '{{ idx_tag }}_SLAVE', target: 'idx-slave' }
########## Apps for IDX master #########
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'idx-cm' }
      - { project: 'zero-id', repo: 'zero_IDX-cluster', branch: '{{ idx_tag }}_MASTER', target: 'idx-cm' }
      - { project: 'zero-sb', repo: 'Splunk_TA_nix', branch: 'sz-monitor', target: 'idx-cm' }
########## Apps for DCNs ###########
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'dcn' }
      - { project: 'zero-sb', repo: 'Splunk_TA_nix', branch: 'sz-monitor', target: 'dcn' }
########## Apps for Syslog ###########
      - { project: 'zero-id', repo: 'zero_syslog_sv3', branch: 'master', target: 'dcn-syslog' }
      - { project: 'zero-id', repo: 'zero_syslog_sv5', branch: 'master', target: 'dcn-syslog' }
########## Apps for HFs ###########
      - { project: 'zero-id', repo: 'zero_auth_ldap', branch: 'master', target: 'hf' }
########## vars for auth ##########
#    dev_group: SG-IT-SplunkZero-PERM-appinspect-DEV
#    pwr_group: SG-IT-SplunkZero-PERM-appinspect-PWR
#    usr_group: DG-IT-SplunkZero-PERM-appinspect-USR
# this variable is the AD group modifier for search head perms
#    team: sgs
#    okta_domain: splunk.okta.com
#    okta_chic_key: splunkinc_splunkzeroglobalsecurityes_1/exk1cu1bfzja1dtXL1d8
#    uri: configured in host file
  become: yes
  roles:
    - { role: yum_install-os-apps, when: spl_role == 'dcn_syslog' }
    - splunk_build_fetcher-version
    - splunk_gen_update-core
    - { role: splunk-CHG-dftpass, when: splunk_version < 7.1.0 }
    - configure_host_vars
    - { role: configure_open_ports, when: host_loc == 'NULL' }
    - splunk_gen_conf-lic-slave
    - { role: splunk_gen_conf_auth-saml, when: spl_role == 'prd_sh' }
    - configure_THP
    - configure_file-descriptors
    - configure_git-management
    - splunk_gen_update-repo-apps
    - { role: splunk_gen_conf-certs, when: host_loc is not defined }
    # - configure_shell_user_nopass
    - { role: configure_syslog, when: spl_role == 'dcn_syslog' }
#    - { role: configure_shell_access, when: spl_role == 'dev_sh' }
#    - splunk_sh_conf_dev-sh
    - { role: splunk_shc_init, when: (spl_role is defined and (spl_role == 'shc_cap' or spl_role == 'shc_mem')) }
    - splunk_gen_restart
    - { role: splunk_shc_cap_election, when: spl_role == 'shc_cap' }
    - { role: splunk_shc_add-member, when: spl_role == 'shc_mem' }


# - include: splunk_sh_add_search-peers-srv_mon.yml
#   vars:
#     uri: https://sv3-prdv-splk-903.sv.splunk.com
#     mgmt_port: 8089

#- include: splunk_sh_install-itsi.yml
