---

- hosts: prod_shc_resync
  become: yes
  vars:
    user: splunk
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
    splunk_user: splunk
    auth_cred: admin:Splunk3r
  roles:
    - splunk_shc_resync_node
