---

- hosts: products_apl
  vars:
    user: splunkzero
    user_group: splunkzero
#    ansible_user: splunk
#    ansible_ssh_private_key_file: ~/.ssh/splunk.key
    deploy_dir: shcluster/apps
    target_uri: {{ groups['products_shc'][0] }}
    app_packages:
      - { project: 'zero-id', repo: 'zero_idx-cluster', branch: 'PRODUCTS_SEARCH'}
      - { project: 'zero-id', repo: 'zero_SHC-cluster', branch: 'PRODUCTS_SH'}
      - { project: 'zero-id', repo: 'zero_prod', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_dsa', branch: 'df_changes'}
      - { project: 'zero-id', repo: 'zero_rolemap', branch: 'master'}
      - { project: 'zero-id', repo: '01-gold_shc', branch: 'master'}
      - { project: 'zero-id', repo: '01-rolemap_perm', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_auth_saml', branch: 'non-ssl'}
      - { project: 'zero-ed', repo: 'website_monitoring', branch: 'master'}
      - { project: 'zero-ed', repo: 'ARTs', branch: 'master' }
      - { project: 'zero-ed', repo: 'hipchat_alerts', branch: 'master' }
      - { project: 'zero-ed', repo: 'products_qti_authorize', branch: 'master' }
      - { project: 'zero-ed', repo: 'cuviz_status_matrix', branch: 'master' }
      - { project: 'zero-ed', repo: 'jira', branch: 'master' }
      - { project: 'zero-ed', repo: 'splunkqa', branch: 'master' }
      - { project: 'zero-ed', repo: 'splunk_app_jenkins', branch: 'master' }
      - { project: 'zero-ed', repo: 'simple_xml_examples', branch: 'master' }
      - { project: 'zero-ed', repo: 'qti-ops', branch: 'master' }
      - { project: 'zero-id', repo: 'Migration_UAT', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_idx-dcn', branch: 'master'}
      - { project: 'zero-ed', repo: 'app_performance', branch: 'master'  }
      - { project: 'zero-ed', repo: 'horizon_chart_app', branch: 'master'  }
      - { project: 'zero-ed', repo: 'network_topology', branch: 'master'  }
      - { project: 'zero-ed', repo: 'products_ucp_authorize', branch: 'master'  }
      - { project: 'zero-ed', repo: 'punchcard_app', branch: 'master'  }
      - { project: 'zero-ed', repo: 'status_indicator_app', branch: 'master'  }
      - { project: 'zero-ed', repo: 'timeline_app', branch: 'master'  }
      - { project: 'zero-ed', repo: 'splunk_app_infrastructure', branch: 'master'}
      - { project: 'zero-ed', repo: 'splunk_app_ucp', branch: 'master'}
      - { project: 'zero-id', repo: 'splunk_sa_cim', branch: 'master' }
      - { project: 'zero-ed', repo: 'splunk_entity_monitoring', branch: 'master'}
      - { project: 'zero-ed', repo: 'is-ops', branch: 'master'}
      - { project: 'zero-ed', repo: 'calendar_heatmap_app', branch: 'master'}
      - { project: 'zero-ed', repo: 'cloud_operations', branch: 'master'}
      - { project: 'zero-ed', repo: 'client_platform_monitoring', branch: 'master'}
      - { project: 'zero-ed', repo: 'continuous_delivery', branch: 'master'}
      - { project: 'zero-ed', repo: 'dd-ops', branch: 'master'}
      - { project: 'zero-ed', repo: 'everywhere', branch: 'master' }
      - { project: 'zero-ed', repo: 'p4stats', branch: 'master' }
      - { project: 'zero-ed', repo: 'prodsec', branch: 'master' }
      - { project: 'zero-ed', repo: 'solutionsprojtracking', branch: 'master'}
      - { project: 'zero-ed', repo: 'splx_jenkins', branch: 'master' }
      - { project: 'zero-ed', repo: 'splx_stash', branch: 'master' }
      - { project: 'zero-ed', repo: 'jira2', branch: 'master' }
      - { project: 'zero-ed', repo: 'jira3', branch: 'master' }
      - { project: 'zero-ed', repo: 'aplura_viz_encrypted_credentials', branch: 'master'}
      - { project: 'zero-ed', repo: 'splunk_app_perf_automation', branch: 'master'}
      - { project: 'zero-id', repo: 'TA-SyncKVStore', branch: 'master'}
      - { project: 'zero-id', repo: '01-rolemap_products', branch: 'master'}
      - { project: 'tools', repo: 'app-highview', branch: 'release'}
#    app_decom:
#      - { project: 'zero-id', repo: 'zero_dsa' }
#    app_backup:
#      - { project: 'zero-cm', repo: 'shc-apps', branch: 'backup' }
#    message: backup
  roles:
    - configure_host_vars
    - configure_git-management
#    - { role: splunk_gen_backup-local }
    - { role: splunk_shc_update-group-apps, when: result|changed }
    - { role: splunk_gen_update-repo-apps, when: result|changed }
#    - { role: splunk_gen_decom-apps, when: result|changed }
    - { role: splunk_shc_app_deploy, when: result|changed }
