---

- hosts: marketing_apl
  vars:
    user: splunk
    user_group: wheel
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
    deploy_dir: shcluster/apps
    app_packages:
      - { project: 'zero-id', repo: 'zero_idx-cluster', branch: 'GEN-PRD_SEARCH'}
      - { project: 'zero-id', repo: 'zero_SHC-cluster', branch: 'MARKETING_SH'}
      - { project: 'zero-id', repo: 'zero_prod', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_dsa', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_rolemap', branch: 'master'}
      - { project: 'zero-id', repo: '01-gold_shc', branch: 'master'}
      - { project: 'zero-id', repo: '01-rolemap_perm', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_auth_saml', branch: 'develop'}
      - { project: 'zero-id', repo: 'splunk_app_db_connect', branch: 'master'}
      - { project: 'zero-id', repo: 'Arcade', branch: 'master'}
      - { project: 'zero-id', repo: 'ArcadeManager', branch: 'master'}
      - { project: 'zero-id', repo: 'ArcadeMasterView', branch: 'master'} 
      - { project: 'zero-id', repo: 'parallel_coordinates_app', branch: 'master'}
      - { project: 'zero-id', repo: 'score_card', branch: 'master'}
#    app_decom:
#      - { project: 'zero-id', repo: 'zero_dsa' }
#    app_backup:
#      - { project: 'zero-cm', repo: 'shc-apps', branch: 'backup' }
#    message: backup
  roles:
    - configure_host_vars
    - configure_git-management
#    - { role: splunk_gen_backup-local }
    - { role: splunk_shc_update-group-apps, when: result|changed }
    - { role: splunk_gen_update-repo-apps, when: result|changed }
#    - { role: splunk_gen_decom-apps, when: result|changed }
    - { role: splunk_shc_app_deploy, when: result|changed }

