---

- hosts: marketing_shc
  become: yes
  vars:
    user: splunk
    user_group: wheel
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
  roles:
    - splunk_shc_init
    - splunk_gen_restart