---

- hosts: products_shc
#  serial: 4
  become: yes
  vars:
    user: splunkzero
    user_group: splunkzero
#    ansible_user: splunkzero
#    ansible_ssh_private_key_file: ~/.ssh/splunk.key
    deploy_dir: apps
    app_decom:
      - { project: 'zero-ed', repo: 'app_performance' }
  roles:
    # - configure_git-management
    # - { role: splunk_gen_update-repo-apps, when: result is changed }
    - { role: splunk_gen_decom-apps }
    - { role: splunk_gen_restart }
# listed apps from ITSI 2.6.0 make sure to add apps that are added in later builds
#    clustered_splunk_apps: [ 'SA-ITSI-CustomModuleViz', 'DA-ITSI-STORAGE', 'DA-ITSI-APPSERVER', 'DA-ITSI-DATABASE', 'DA-ITSI-EUEM', 'DA-ITSI-LB', 'DA-ITSI-OS', 'DA-ITSI-VIRTUALIZATION', 'DA-ITSI-WEBSERVER', 'DA-ITSI-WebServices', 'itsi', 'SA-IndexCreation', 'SA-ITOA', 'SA-ITSI-ATAD', 'SA-ITSI-Licensechecker', 'SA-ITSI-MetricAD', 'SA-UserAccess', 'Splunk_SA_CIM', 'Splunk_TA_webservices' ]
