---

- hosts: stage_shc_cap
  vars:
    user: splunk
    user_group: wheel
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
    deploy_dir: shcluster/apps
    message: "test"
    app_packages:
      - { project: 'zero-cm', repo: 'search_apps', branch: 'stage'}
      - { project: 'zero-id', repo: 'zero_stage', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_rolemap', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_app_mon', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_dsa', branch: 'master'}
      - { project: 'zero-id', repo: 'spl_replay', branch: 'master'}
      - { project: 'zero-id', repo: 'zero_auth_saml', branch: 'master'}
    app_decom:
      - { project: '', repo: '' }
    app_backup:
      - { project: 'zero-cm', repo: 'shc-apps', branch: 'backup' }
  roles:
#    - configure_git-management
    - splunk_gen_backup-local
#    - { role: splunk_shc_update-group-apps, when: result|changed }
#    - { role: splunk_gen_update-repo-apps, when: result|changed }
#    - { role: splunk_gen_decom-apps, when: result|changed }
#    - { role: splunk_shc_app_deploy, when: result|changed }
 
