---

- hosts: sv3_hf
  become: yes
  vars:
    user: splunk
    user_group: wheel
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
    tar_name: '{{ backup_dir }}_{{ inventory_hostname }}'
    tar_dir_path: '{{ backup_dir }}'
    splunk_version: 7.1.0
    splunk_branch: current
    os_platform: linux-3.10-x86_64.rpm
    installer: '{{ splunk_pkg }}'
    url: '{{ splunk_dl }}'
    backup_dirs:
      - { folder: 'apps', target: 'all' }
      - { folder: 'auth', target: 'all' }
      - { folder: 'system/local', target: 'all' }
      - { folder: 'instance.cfg', target: 'all' }
      - { folder: 'deployment-apps', target: 'prd-sh' }
      - { folder: 'shcluster', target: 'shc-dp' }
      - { folder: 'master-apps', target: 'idx-cm' }
      - { folder: 'slave-apps', target: 'idx-slave' }

  roles:
    - configure_host_vars
    - splunk_gen_backup-prep
    - splunk_gen_backup-apps
    - splunk_gen_backup-deploy-apps
    - splunk_gen_backup-instance
#    - splunk_gen_version-rollback
    - tar-compress
    - box-upload
