---

- hosts: zero_app-inspect
  become: yes
  vars:
    user: splunk
    user_group: wheel
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
# upgrade varaibles
    # splunk_version: 7.1.0
    # splunk_branch: current
    # os_platform: linux-3.10-x86_64.rpm
    # installer: '{{ splunk_pkg }}'
    # url: '{{ splunk_dl }}'
    yum_packages:
      - { name: 'python-pip' }
    pip_packages:
      - { name: 'virtualenv' }
  roles:
    - yum_install-os-apps
    - pip_install
    - configure_app-inspect
