---

- hosts: sv3_syslog
  become: yes
  vars:
    user: splunk
    user_group: wheel
    ansible_user: splunk
    ansible_ssh_private_key_file: ~/.ssh/splunk.key
  roles:
    - configure_host_vars
    - splunk_gen_sanitize-apps
