---

- name: write LDAP stanza to system local auth
  lineinfile: 
   dest: /opt/splunk/etc/system/local/authentication.conf 
   state: present
   insertafter: EOF
   create: yes 
   owner: splunk
   group: splunk
   line: "[roleMap_SplunkCorp]"

- name: write SLO to system local auth
  lineinfile: 
   dest: /opt/splunk/etc/system/local/authentication.conf 
   insertafter: "[roleMap_SplunkCorp]" 
   line: "user = {{ api_user }}"

# - name: write SLO to system local auth
#   lineinfile: 
#    dest: /opt/splunk/etc/system/local/authentication.conf 
#    insertafter: "[rolemap_saml]" 
#    line: "developer = {{ pwr_group }}"

# - name: write SSO to system local auth
#   lineinfile: 
#    dest: {{ splunk_home }}/etc/system/local/authentication.conf 
#    insertafter: "[roleMap_SplunkCorp]" 
#    line: "user = {{ usr_group }}"
