---

# - name: remove old checkout
#   become: yes
#   shell: rm -rf {{ splunk_home }}/etc/{{ deploy_dir }}/*

# - name: Copy repo apps to deploy directory
#   become: yes
#   shell: cp -r {{ splunk_home }}/repo/{{ deploy_dir }}/apps/* {{ splunk_home }}/etc/{{ deploy_dir }}/

#- name: set splunk etc dir owner to splunk
#  become: yes
#  shell: chown -R splunk:splunk {{ splunk_home }}/etc/

- name: set directory ownership to splunk
  file:
    path: '{{ splunk_home }}/etc/shcluster/apps'
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  become: yes

## ready for sh deploy command!

- name: deploy app updates to cluster
  become: yes
  command: sudo -u {{ splunk_user }} {{ splunk_home }}/bin/splunk apply shcluster-bundle --answer-yes -target {{ target_uri }}:{{ mgmt_port }} -preserve-lookups true -auth "{{ splunk_cred }}"
  register: result1
  when:
    - preserve_lookups == "yes"
  ignore_errors: yes

- name: retry - deploy app updates to cluster
  become: yes
  command: sudo -u {{ splunk_user }} {{ splunk_home }}/bin/splunk apply shcluster-bundle --answer-yes -target {{ target_uri }}:{{ mgmt_port }} -preserve-lookups true -auth "{{ splunk_cred }}"
  when:
    - result1 is failed
    - preserve_lookups == "yes"
  register: result2
  ignore_errors: yes

- name: final retry - deploy app updates to cluster
  become: yes
  command: sudo -u {{ splunk_user }} {{ splunk_home }}/bin/splunk apply shcluster-bundle --answer-yes -target {{ target_uri }}:{{ mgmt_port }} -preserve-lookups true -auth "{{ splunk_cred }}"
  when:
    - result2 is failed
    - preserve_lookups == "yes"


## ready for sh deploy command!

- name: deploy app updates to cluster (non-preserved)
  become: yes
  command: sudo -u {{ splunk_user }} {{ splunk_home }}/bin/splunk apply shcluster-bundle --answer-yes -target {{ target_uri }}:{{ mgmt_port }} true -auth "{{ splunk_cred }}"
  register: result1
  when:
    - preserve_lookups == "no"
  ignore_errors: yes

- name: retry - deploy app updates to cluster (non-preserved)
  become: yes
  command: sudo -u {{ splunk_user }} {{ splunk_home }}/bin/splunk apply shcluster-bundle --answer-yes -target {{ target_uri }}:{{ mgmt_port }} -auth "{{ splunk_cred }}"
  when:
    - result1 is failed
    - preserve_lookups == "no"
  register: result2
  ignore_errors: yes

- name: final retry - deploy app updates to cluster (non-preserved)
  become: yes
  command: sudo -u {{ splunk_user }} {{ splunk_home }}/bin/splunk apply shcluster-bundle --answer-yes -target {{ target_uri }}:{{ mgmt_port }} -auth "{{ splunk_cred }}"
  when:
    - result2 is failed
    - preserve_lookups == "no"
