---

- name: check that backup folder exists
  stat:
    path: "{{ backup_path }}"
  register: backup_present

- name: backup system local folder
  become: yes
#  command: cp -r {{ splunk_home }}/etc/system/local {{ backup_dir }}/system/
  synchronize:
    src: '{{ splunk_home }}/etc/system/local'
    dest: '{{ backup_path }}/system/'
    rsync_path: "su -c rsync"
  delegate_to: "{{ inventory_hostname }}"
  when: backup_present.stat.exists == True

- name: backup instance file
  become: yes
#  command: cp -r {{ splunk_home }}/etc/instance.cfg {{ splunk_home }}/backup/
  synchronize:
    src: '{{ splunk_home }}/etc/instance.cfg'
    dest: '{{ backup_path }}/instance.cfg'
    rsync_path: "su -c rsync"
  delegate_to: "{{ inventory_hostname }}"
  when: backup_present.stat.exists == True

- name: backup auth folder
  become: yes
#  command: cp -r {{ splunk_home }}/etc/auth {{ splunk_home }}/backup/
  synchronize:
    src: '{{ splunk_home }}/etc/auth'
    dest: '{{ backup_path }}/'
    rsync_path: "su -c rsync"
  delegate_to: "{{ inventory_hostname }}"
  when: backup_present.stat.exists == True

- name: backup users folder
  become: yes
#  command: cp -r {{ splunk_home }}/etc/users {{ splunk_home }}/backup/
  synchronize:
    src: '{{ splunk_home }}/etc/users'
    dest: '{{ backup_path }}/'
    rsync_path: "su -c rsync"
  delegate_to: "{{ inventory_hostname }}"
  when: backup_present.stat.exists == True
