---


# - name: enable maintenance mode
#   shell: sudo -H -u {{ splunk_user }} {{ splunk_home }}/bin/splunk enable maintenance-mode -auth admin:Splunk3r

#- name: remove managed apps
#  become: yes
#  shell: rm -rf {{ splunk_home }}/etc/master-apps/*
# this command supports the master-apps directory and the shcluster/apps directory

#- name: update managed apps
#  become: yes
#  shell: cp -r {{ splunk_home}}/repo/{{ repo }}/* {{ splunk_home }}/etc/master-apps/ 

# depreciated, use file command
#- name: set app owner
#  become: yes
#  shell: chown -R splunk:splunk {{ splunk_home }}/etc/{{ deploy_dir }}

- name: set ownership on apps directory
  file:
    path: '{{ splunk_home }}/etc/{{ deploy_dir }}'
    state: directory
    recurse: yes
    owner: splunk
    group: splunk
  become: yes

- name: deploy app updates to cluster
  become: yes
  shell: sudo -H -u {{ splunk_user }} {{ splunk_home }}/bin/splunk apply cluster-bundle --answer-yes --skip-validation
  